{{- if .Values.otelGateway.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability-gp-mini.otelGateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-gp-mini.componentLabels" (dict "ctx" . "component" "otel-gateway") | nindent 4 }}
  {{- with .Values.otelGateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
