{{- if .Values.control.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.control.fullnameOverride }}
  namespace: {{ .Values.control.namespace }}
  labels:
    app: {{ .Values.control.fullnameOverride }}
    {{- include "rotelle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.control.service.type }}
  selector:
    app: {{ .Values.control.fullnameOverride }}
  ports:
    - name: control
      port: {{ .Values.control.service.port }}
      targetPort: control
{{- end }}
