{{- if .Values.otelNodeCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "observability-gp-mini.otelNodeCollector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-gp-mini.componentLabels" (dict "ctx" . "component" "otel-node-collector") | nindent 4 }}
  {{- with .Values.otelNodeCollector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
